<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

class BpmSeeder extends BaseSeeder
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('bpms')->insert([
            0 => [
                'id'                        => 1,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2018',
                'co2_min'                   => 0,
                'co2_max'                   => 73,
                'sum_amount'                => 356,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            1 => [
                'id'                        => 2,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2018',
                'co2_min'                   => 73,
                'co2_max'                   => 98,
                'sum_amount'                => 502,
                'multiply_amount'           => 63,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            2 => [
                'id'                        => 3,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2018',
                'co2_min'                   => 98,
                'co2_max'                   => 144,
                'sum_amount'                => 2077,
                'multiply_amount'           => 139,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            3 => [
                'id'                        => 4,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2018',
                'co2_min'                   => 144,
                'co2_max'                   => 162,
                'sum_amount'                => 8471,
                'multiply_amount'           => 229,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            4 => [
                'id'                        => 5,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2018',
                'co2_min'                   => 162,
                'co2_max'                   => null,
                'sum_amount'                => 12593,
                'multiply_amount'           => 458,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            5 => [
                'id'                        => 6,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2018',
                'co2_min'                   => 0,
                'co2_max'                   => 73,
                'sum_amount'                => 356,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            6 => [
                'id'                        => 7,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2018',
                'co2_min'                   => 73,
                'co2_max'                   => 98,
                'sum_amount'                => 502,
                'multiply_amount'           => 63,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            7 => [
                'id'                        => 8,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2018',
                'co2_min'                   => 98,
                'co2_max'                   => 144,
                'sum_amount'                => 2077,
                'multiply_amount'           => 139,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            8 => [
                'id'                        => 9,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2018',
                'co2_min'                   => 144,
                'co2_max'                   => 162,
                'sum_amount'                => 8471,
                'multiply_amount'           => 229,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            9 => [
                'id'                        => 10,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2018',
                'co2_min'                   => 162,
                'co2_max'                   => null,
                'sum_amount'                => 12593,
                'multiply_amount'           => 458,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            10 => [
                'id'                        => 11,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2018',
                'co2_min'                   => 0,
                'co2_max'                   => 30,
                'sum_amount'                => 0,
                'multiply_amount'           => 19,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            11 => [
                'id'                        => 12,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2018',
                'co2_min'                   => 30,
                'co2_max'                   => 50,
                'sum_amount'                => 570,
                'multiply_amount'           => 87,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            12 => [
                'id'                        => 13,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2018',
                'co2_min'                   => 50,
                'co2_max'                   => null,
                'sum_amount'                => 2310,
                'multiply_amount'           => 289,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            13 => [
                'id'                        => 14,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2018',
                'co2_min'                   => 0,
                'co2_max'                   => 30,
                'sum_amount'                => 0,
                'multiply_amount'           => 19,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            14 => [
                'id'                        => 15,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2018',
                'co2_min'                   => 30,
                'co2_max'                   => 50,
                'sum_amount'                => 570,
                'multiply_amount'           => 87,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            15 => [
                'id'                        => 16,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2018',
                'co2_min'                   => 50,
                'co2_max'                   => null,
                'sum_amount'                => 2310,
                'multiply_amount'           => 289,
                'min_co2_to_add_diesel_tax' => 63,
                'additional_diesel_tax'     => '87.38',
            ],
            16 => [
                'id'                        => 17,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2019',
                'co2_min'                   => 0,
                'co2_max'                   => 71,
                'sum_amount'                => 360,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            17 => [
                'id'                        => 18,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2019',
                'co2_min'                   => 71,
                'co2_max'                   => 96,
                'sum_amount'                => 502,
                'multiply_amount'           => 60,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            18 => [
                'id'                        => 19,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2019',
                'co2_min'                   => 95,
                'co2_max'                   => 139,
                'sum_amount'                => 1942,
                'multiply_amount'           => 131,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            19 => [
                'id'                        => 20,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2019',
                'co2_min'                   => 139,
                'co2_max'                   => 156,
                'sum_amount'                => 7706,
                'multiply_amount'           => 215,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            20 => [
                'id'                        => 21,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2019',
                'co2_min'                   => 156,
                'co2_max'                   => null,
                'sum_amount'                => 11361,
                'multiply_amount'           => 429,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            21 => [
                'id'                        => 22,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2019',
                'co2_min'                   => 0,
                'co2_max'                   => 71,
                'sum_amount'                => 360,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            22 => [
                'id'                        => 23,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2019',
                'co2_min'                   => 71,
                'co2_max'                   => 96,
                'sum_amount'                => 502,
                'multiply_amount'           => 60,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            23 => [
                'id'                        => 24,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2019',
                'co2_min'                   => 95,
                'co2_max'                   => 139,
                'sum_amount'                => 1942,
                'multiply_amount'           => 131,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            24 => [
                'id'                        => 25,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2019',
                'co2_min'                   => 139,
                'co2_max'                   => 156,
                'sum_amount'                => 7706,
                'multiply_amount'           => 215,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            25 => [
                'id'                        => 26,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2019',
                'co2_min'                   => 156,
                'co2_max'                   => null,
                'sum_amount'                => 11361,
                'multiply_amount'           => 429,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            26 => [
                'id'                        => 27,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2019',
                'co2_min'                   => 0,
                'co2_max'                   => 30,
                'sum_amount'                => 0,
                'multiply_amount'           => 27,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            27 => [
                'id'                        => 28,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2019',
                'co2_min'                   => 30,
                'co2_max'                   => 50,
                'sum_amount'                => 810,
                'multiply_amount'           => 113,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            28 => [
                'id'                        => 29,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2019',
                'co2_min'                   => 50,
                'co2_max'                   => null,
                'sum_amount'                => 3070,
                'multiply_amount'           => 271,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            29 => [
                'id'                        => 30,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2019',
                'co2_min'                   => 0,
                'co2_max'                   => 30,
                'sum_amount'                => 0,
                'multiply_amount'           => 27,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            30 => [
                'id'                        => 31,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2019',
                'co2_min'                   => 30,
                'co2_max'                   => 50,
                'sum_amount'                => 810,
                'multiply_amount'           => 113,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            31 => [
                'id'                        => 32,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2019',
                'co2_min'                   => 50,
                'co2_max'                   => null,
                'sum_amount'                => 3070,
                'multiply_amount'           => 271,
                'min_co2_to_add_diesel_tax' => 61,
                'additional_diesel_tax'     => '88.43',
            ],
            32 => [
                'id'                        => 33,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2020',
                'co2_min'                   => 0,
                'co2_max'                   => 90,
                'sum_amount'                => 366,
                'multiply_amount'           => 1,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            33 => [
                'id'                        => 34,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2020',
                'co2_min'                   => 90,
                'co2_max'                   => 116,
                'sum_amount'                => 456,
                'multiply_amount'           => 57,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            34 => [
                'id'                        => 35,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2020',
                'co2_min'                   => 116,
                'co2_max'                   => 162,
                'sum_amount'                => 1938,
                'multiply_amount'           => 124,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            35 => [
                'id'                        => 36,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2020',
                'co2_min'                   => 162,
                'co2_max'                   => 180,
                'sum_amount'                => 7642,
                'multiply_amount'           => 204,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            36 => [
                'id'                        => 37,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2020',
                'co2_min'                   => 180,
                'co2_max'                   => null,
                'sum_amount'                => 11314,
                'multiply_amount'           => 408,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            37 => [
                'id'                        => 38,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2020',
                'co2_min'                   => 0,
                'co2_max'                   => 90,
                'sum_amount'                => 366,
                'multiply_amount'           => 1,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            38 => [
                'id'                        => 39,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2020',
                'co2_min'                   => 90,
                'co2_max'                   => 116,
                'sum_amount'                => 456,
                'multiply_amount'           => 57,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            39 => [
                'id'                        => 40,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2020',
                'co2_min'                   => 116,
                'co2_max'                   => 162,
                'sum_amount'                => 1938,
                'multiply_amount'           => 124,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            40 => [
                'id'                        => 41,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2020',
                'co2_min'                   => 162,
                'co2_max'                   => 180,
                'sum_amount'                => 7642,
                'multiply_amount'           => 204,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            41 => [
                'id'                        => 42,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2020',
                'co2_min'                   => 180,
                'co2_max'                   => null,
                'sum_amount'                => 11314,
                'multiply_amount'           => 408,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            42 => [
                'id'                        => 43,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2020',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 24,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            43 => [
                'id'                        => 44,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2020',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 816,
                'multiply_amount'           => 83,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            44 => [
                'id'                        => 45,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2020',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 2974,
                'multiply_amount'           => 199,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            45 => [
                'id'                        => 46,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2020',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 24,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            46 => [
                'id'                        => 47,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2020',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 816,
                'multiply_amount'           => 83,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            47 => [
                'id'                        => 48,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2020',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 2974,
                'multiply_amount'           => 199,
                'min_co2_to_add_diesel_tax' => 80,
                'additional_diesel_tax'     => '78.82',
            ],
            48 => [
                'id'                        => 49,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2021',
                'co2_min'                   => 0,
                'co2_max'                   => 86,
                'sum_amount'                => 372,
                'multiply_amount'           => 1,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            49 => [
                'id'                        => 50,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2021',
                'co2_min'                   => 86,
                'co2_max'                   => 111,
                'sum_amount'                => 458,
                'multiply_amount'           => 60,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            50 => [
                'id'                        => 51,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2021',
                'co2_min'                   => 111,
                'co2_max'                   => 155,
                'sum_amount'                => 1958,
                'multiply_amount'           => 132,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            51 => [
                'id'                        => 52,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2021',
                'co2_min'                   => 155,
                'co2_max'                   => 172,
                'sum_amount'                => 7766,
                'multiply_amount'           => 216,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            52 => [
                'id'                        => 53,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2021',
                'co2_min'                   => 172,
                'co2_max'                   => null,
                'sum_amount'                => 11438,
                'multiply_amount'           => 432,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            53 => [
                'id'                        => 54,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2021',
                'co2_min'                   => 0,
                'co2_max'                   => 86,
                'sum_amount'                => 372,
                'multiply_amount'           => 1,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            54 => [
                'id'                        => 55,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2021',
                'co2_min'                   => 86,
                'co2_max'                   => 111,
                'sum_amount'                => 458,
                'multiply_amount'           => 60,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            55 => [
                'id'                        => 56,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2021',
                'co2_min'                   => 111,
                'co2_max'                   => 155,
                'sum_amount'                => 1958,
                'multiply_amount'           => 132,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            56 => [
                'id'                        => 57,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2021',
                'co2_min'                   => 155,
                'co2_max'                   => 172,
                'sum_amount'                => 7766,
                'multiply_amount'           => 216,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            57 => [
                'id'                        => 58,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2021',
                'co2_min'                   => 172,
                'co2_max'                   => null,
                'sum_amount'                => 11438,
                'multiply_amount'           => 432,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            58 => [
                'id'                        => 59,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2021',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 24,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            59 => [
                'id'                        => 60,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2021',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 816,
                'multiply_amount'           => 84,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            60 => [
                'id'                        => 61,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2021',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3000,
                'multiply_amount'           => 202,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            61 => [
                'id'                        => 62,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2021',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 24,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            62 => [
                'id'                        => 63,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2021',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 816,
                'multiply_amount'           => 84,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            63 => [
                'id'                        => 64,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2021',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3000,
                'multiply_amount'           => 202,
                'min_co2_to_add_diesel_tax' => 77,
                'additional_diesel_tax'     => '83.59',
            ],
            64 => [
                'id'                        => 65,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2022',
                'co2_min'                   => 0,
                'co2_max'                   => 84,
                'sum_amount'                => 376,
                'multiply_amount'           => 1,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            65 => [
                'id'                        => 66,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2022',
                'co2_min'                   => 84,
                'co2_max'                   => 109,
                'sum_amount'                => 460,
                'multiply_amount'           => 62,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            66 => [
                'id'                        => 67,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2022',
                'co2_min'                   => 109,
                'co2_max'                   => 152,
                'sum_amount'                => 2010,
                'multiply_amount'           => 137,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            67 => [
                'id'                        => 68,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2022',
                'co2_min'                   => 152,
                'co2_max'                   => 168,
                'sum_amount'                => 7901,
                'multiply_amount'           => 224,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            68 => [
                'id'                        => 69,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2022',
                'co2_min'                   => 168,
                'co2_max'                   => null,
                'sum_amount'                => 11485,
                'multiply_amount'           => 448,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            69 => [
                'id'                        => 70,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2022',
                'co2_min'                   => 0,
                'co2_max'                   => 84,
                'sum_amount'                => 376,
                'multiply_amount'           => 1,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            70 => [
                'id'                        => 71,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2022',
                'co2_min'                   => 84,
                'co2_max'                   => 109,
                'sum_amount'                => 460,
                'multiply_amount'           => 62,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            71 => [
                'id'                        => 72,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2022',
                'co2_min'                   => 109,
                'co2_max'                   => 152,
                'sum_amount'                => 2010,
                'multiply_amount'           => 137,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            72 => [
                'id'                        => 73,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2022',
                'co2_min'                   => 152,
                'co2_max'                   => 168,
                'sum_amount'                => 7901,
                'multiply_amount'           => 224,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            73 => [
                'id'                        => 74,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2022',
                'co2_min'                   => 168,
                'co2_max'                   => null,
                'sum_amount'                => 11485,
                'multiply_amount'           => 448,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            74 => [
                'id'                        => 75,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2022',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 24,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            75 => [
                'id'                        => 76,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2022',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 816,
                'multiply_amount'           => 85,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            76 => [
                'id'                        => 77,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2022',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3026,
                'multiply_amount'           => 204,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            77 => [
                'id'                        => 78,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2022',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 24,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            78 => [
                'id'                        => 79,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2022',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 816,
                'multiply_amount'           => 85,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            79 => [
                'id'                        => 80,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2022',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3026,
                'multiply_amount'           => 204,
                'min_co2_to_add_diesel_tax' => 75,
                'additional_diesel_tax'     => '86.67',
            ],
            80 => [
                'id'                        => 81,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2023',
                'co2_min'                   => 0,
                'co2_max'                   => 82,
                'sum_amount'                => 400,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            81 => [
                'id'                        => 82,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2023',
                'co2_min'                   => 82,
                'co2_max'                   => 106,
                'sum_amount'                => 564,
                'multiply_amount'           => 68,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            82 => [
                'id'                        => 83,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2023',
                'co2_min'                   => 106,
                'co2_max'                   => 148,
                'sum_amount'                => 2196,
                'multiply_amount'           => 149,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            83 => [
                'id'                        => 84,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2023',
                'co2_min'                   => 148,
                'co2_max'                   => 165,
                'sum_amount'                => 8454,
                'multiply_amount'           => 244,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            84 => [
                'id'                        => 85,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2023',
                'co2_min'                   => 165,
                'co2_max'                   => null,
                'sum_amount'                => 12602,
                'multiply_amount'           => 488,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            85 => [
                'id'                        => 86,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2023',
                'co2_min'                   => 0,
                'co2_max'                   => 82,
                'sum_amount'                => 400,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            86 => [
                'id'                        => 87,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2023',
                'co2_min'                   => 82,
                'co2_max'                   => 106,
                'sum_amount'                => 564,
                'multiply_amount'           => 68,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            87 => [
                'id'                        => 88,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2023',
                'co2_min'                   => 106,
                'co2_max'                   => 148,
                'sum_amount'                => 2196,
                'multiply_amount'           => 149,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            88 => [
                'id'                        => 89,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2023',
                'co2_min'                   => 148,
                'co2_max'                   => 165,
                'sum_amount'                => 8454,
                'multiply_amount'           => 244,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            89 => [
                'id'                        => 90,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2023',
                'co2_min'                   => 165,
                'co2_max'                   => null,
                'sum_amount'                => 12602,
                'multiply_amount'           => 488,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            90 => [
                'id'                        => 91,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2023',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 26,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            91 => [
                'id'                        => 92,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2023',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 884,
                'multiply_amount'           => 91,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            92 => [
                'id'                        => 93,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2023',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3250,
                'multiply_amount'           => 217,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            93 => [
                'id'                        => 94,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2023',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 26,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            94 => [
                'id'                        => 95,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2023',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 884,
                'multiply_amount'           => 91,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],
            95 => [
                'id'                        => 96,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2023',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3250,
                'multiply_amount'           => 217,
                'min_co2_to_add_diesel_tax' => 73,
                'additional_diesel_tax'     => '94.30',
            ],

            96 => [
                'id'                        => 97,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2024',
                'co2_min'                   => 0,
                'co2_max'                   => 80,
                'sum_amount'                => 440,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            97 => [
                'id'                        => 98,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2024',
                'co2_min'                   => 80,
                'co2_max'                   => 104,
                'sum_amount'                => 600,
                'multiply_amount'           => 76,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            98 => [
                'id'                        => 99,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2024',
                'co2_min'                   => 104,
                'co2_max'                   => 145,
                'sum_amount'                => 2424,
                'multiply_amount'           => 167,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            99 => [
                'id'                        => 100,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2024',
                'co2_min'                   => 145,
                'co2_max'                   => 161,
                'sum_amount'                => 9271,
                'multiply_amount'           => 274,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            100 => [
                'id'                        => 101,
                'type_id'                   => 1,
                'fuel_type'                 => 1,
                'year'                      => '2024',
                'co2_min'                   => 161,
                'co2_max'                   => null,
                'sum_amount'                => 13655,
                'multiply_amount'           => 549,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            101 => [
                'id'                        => 102,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2024',
                'co2_min'                   => 0,
                'co2_max'                   => 80,
                'sum_amount'                => 440,
                'multiply_amount'           => 2,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
            102 => [
                'id'                        => 103,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2024',
                'co2_min'                   => 80,
                'co2_max'                   => 104,
                'sum_amount'                => 600,
                'multiply_amount'           => 76,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
            103 => [
                'id'                        => 104,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2024',
                'co2_min'                   => 104,
                'co2_max'                   => 145,
                'sum_amount'                => 2424,
                'multiply_amount'           => 167,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
            104 => [
                'id'                        => 105,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2024',
                'co2_min'                   => 145,
                'co2_max'                   => 161,
                'sum_amount'                => 9271,
                'multiply_amount'           => 274,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
            105 => [
                'id'                        => 106,
                'type_id'                   => 1,
                'fuel_type'                 => 2,
                'year'                      => '2024',
                'co2_min'                   => 161,
                'co2_max'                   => null,
                'sum_amount'                => 13655,
                'multiply_amount'           => 549,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],

            106 => [
                'id'                        => 107,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2024',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 28,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            107 => [
                'id'                        => 108,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2024',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 952,
                'multiply_amount'           => 100,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            108 => [
                'id'                        => 109,
                'type_id'                   => 1,
                'fuel_type'                 => 3,
                'year'                      => '2024',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3552,
                'multiply_amount'           => 239,
                'min_co2_to_add_diesel_tax' => null,
                'additional_diesel_tax'     => null,
            ],
            109 => [
                'id'                        => 110,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2024',
                'co2_min'                   => 0,
                'co2_max'                   => 34,
                'sum_amount'                => 0,
                'multiply_amount'           => 28,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
            110 => [
                'id'                        => 111,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2024',
                'co2_min'                   => 34,
                'co2_max'                   => 60,
                'sum_amount'                => 952,
                'multiply_amount'           => 100,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
            111 => [
                'id'                        => 112,
                'type_id'                   => 1,
                'fuel_type'                 => 4,
                'year'                      => '2024',
                'co2_min'                   => 60,
                'co2_max'                   => null,
                'sum_amount'                => 3552,
                'multiply_amount'           => 239,
                'min_co2_to_add_diesel_tax' => 71,
                'additional_diesel_tax'     => '106.07',
            ],
        ]);
    }
}
