<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MakeSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        $makesArray = [
            0 => [
                'id'         => 1,
                'creator_id' => 2,
                'name'       => 'Audi',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            1 => [
                'id'         => 2,
                'creator_id' => 2,
                'name'       => 'BMW',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            2 => [
                'id'         => 3,
                'creator_id' => 2,
                'name'       => 'Cupra',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            3 => [
                'id'         => 4,
                'creator_id' => 2,
                'name'       => 'Fiat',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            4 => [
                'id'         => 5,
                'creator_id' => 2,
                'name'       => 'Ford',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            5 => [
                'id'         => 6,
                'creator_id' => 2,
                'name'       => 'Hyundai',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            6 => [
                'id'         => 7,
                'creator_id' => 2,
                'name'       => 'Kia',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            7 => [
                'id'         => 8,
                'creator_id' => 2,
                'name'       => 'Mercedes-Benz',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            8 => [
                'id'         => 9,
                'creator_id' => 2,
                'name'       => 'MINI',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            9 => [
                'id'         => 10,
                'creator_id' => 2,
                'name'       => 'Nissan',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            10 => [
                'id'         => 11,
                'creator_id' => 2,
                'name'       => 'Opel',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            11 => [
                'id'         => 12,
                'creator_id' => 2,
                'name'       => 'Peugeot',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            12 => [
                'id'         => 13,
                'creator_id' => 2,
                'name'       => 'Renault',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            13 => [
                'id'         => 14,
                'creator_id' => 2,
                'name'       => 'SEAT',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            14 => [
                'id'         => 15,
                'creator_id' => 2,
                'name'       => 'Skoda',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            15 => [
                'id'         => 16,
                'creator_id' => 2,
                'name'       => 'Toyota',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            16 => [
                'id'         => 17,
                'creator_id' => 2,
                'name'       => 'Volkswagen',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            17 => [
                'id'         => 18,
                'creator_id' => 2,
                'name'       => 'Volvo',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            18 => [
                'id'         => 19,
                'creator_id' => 2,
                'name'       => 'Abarth',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            19 => [
                'id'         => 20,
                'creator_id' => 2,
                'name'       => 'AC',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            20 => [
                'id'         => 21,
                'creator_id' => 2,
                'name'       => 'Acura',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            21 => [
                'id'         => 22,
                'creator_id' => 2,
                'name'       => 'Aiways',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            22 => [
                'id'         => 23,
                'creator_id' => 2,
                'name'       => 'Aixam',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            23 => [
                'id'         => 24,
                'creator_id' => 2,
                'name'       => 'Alfa Romeo',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            24 => [
                'id'         => 25,
                'creator_id' => 2,
                'name'       => 'ALPINA',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            25 => [
                'id'         => 26,
                'creator_id' => 2,
                'name'       => 'Alpine',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            26 => [
                'id'         => 27,
                'creator_id' => 2,
                'name'       => 'Ariel',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            27 => [
                'id'         => 28,
                'creator_id' => 2,
                'name'       => 'Artega',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            28 => [
                'id'         => 29,
                'creator_id' => 2,
                'name'       => 'Aston Martin',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            29 => [
                'id'         => 30,
                'creator_id' => 2,
                'name'       => 'Austin Healey',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            30 => [
                'id'         => 31,
                'creator_id' => 2,
                'name'       => 'BAIC',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            31 => [
                'id'         => 32,
                'creator_id' => 2,
                'name'       => 'Bentley',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            32 => [
                'id'         => 33,
                'creator_id' => 2,
                'name'       => 'Bugatti',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            33 => [
                'id'         => 34,
                'creator_id' => 2,
                'name'       => 'Buick',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            34 => [
                'id'         => 35,
                'creator_id' => 2,
                'name'       => 'Brilliance',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            35 => [
                'id'         => 36,
                'creator_id' => 2,
                'name'       => 'BYD',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            36 => [
                'id'         => 37,
                'creator_id' => 2,
                'name'       => 'Cadillac',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            37 => [
                'id'         => 38,
                'creator_id' => 2,
                'name'       => 'Casalini',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            38 => [
                'id'         => 39,
                'creator_id' => 2,
                'name'       => 'Caterham',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            39 => [
                'id'         => 40,
                'creator_id' => 2,
                'name'       => 'Cenntro',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            40 => [
                'id'         => 41,
                'creator_id' => 2,
                'name'       => 'Chatenet',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            41 => [
                'id'         => 42,
                'creator_id' => 2,
                'name'       => 'Chevrolet',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            42 => [
                'id'         => 43,
                'creator_id' => 2,
                'name'       => 'Chrysler',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            43 => [
                'id'         => 44,
                'creator_id' => 2,
                'name'       => 'Citroën',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            44 => [
                'id'         => 45,
                'creator_id' => 2,
                'name'       => 'Cobra',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            45 => [
                'id'         => 46,
                'creator_id' => 2,
                'name'       => 'Corvette',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            46 => [
                'id'         => 47,
                'creator_id' => 2,
                'name'       => 'Dacia',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            47 => [
                'id'         => 48,
                'creator_id' => 2,
                'name'       => 'Daihatsu',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            48 => [
                'id'         => 49,
                'creator_id' => 2,
                'name'       => 'Daimler',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            49 => [
                'id'         => 50,
                'creator_id' => 2,
                'name'       => 'Daewoo',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            50 => [
                'id'         => 51,
                'creator_id' => 2,
                'name'       => 'DeTomaso',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            51 => [
                'id'         => 52,
                'creator_id' => 2,
                'name'       => 'Dodge',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            52 => [
                'id'         => 53,
                'creator_id' => 2,
                'name'       => 'Dongfeng',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            53 => [
                'id'         => 54,
                'creator_id' => 2,
                'name'       => 'Donkervoort',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            54 => [
                'id'         => 55,
                'creator_id' => 2,
                'name'       => 'DFSK',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            55 => [
                'id'         => 56,
                'creator_id' => 2,
                'name'       => 'DS Automobiles',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            56 => [
                'id'         => 57,
                'creator_id' => 2,
                'name'       => 'Elaris',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            57 => [
                'id'         => 58,
                'creator_id' => 2,
                'name'       => 'Estrima',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            58 => [
                'id'         => 59,
                'creator_id' => 2,
                'name'       => 'e.GO',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            59 => [
                'id'         => 60,
                'creator_id' => 2,
                'name'       => 'Ferrari',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            60 => [
                'id'         => 61,
                'creator_id' => 2,
                'name'       => 'Fisker',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            61 => [
                'id'         => 62,
                'creator_id' => 2,
                'name'       => 'GAC',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            62 => [
                'id'         => 63,
                'creator_id' => 2,
                'name'       => 'Gemballa',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            63 => [
                'id'         => 64,
                'creator_id' => 2,
                'name'       => 'Genesis',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            64 => [
                'id'         => 65,
                'creator_id' => 2,
                'name'       => 'GMC',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            65 => [
                'id'         => 66,
                'creator_id' => 2,
                'name'       => 'Gonow',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            66 => [
                'id'         => 67,
                'creator_id' => 2,
                'name'       => 'Grecav',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            67 => [
                'id'         => 68,
                'creator_id' => 2,
                'name'       => 'GWM',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            68 => [
                'id'         => 69,
                'creator_id' => 2,
                'name'       => 'Hamann',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            69 => [
                'id'         => 70,
                'creator_id' => 2,
                'name'       => 'Holden',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            70 => [
                'id'         => 71,
                'creator_id' => 2,
                'name'       => 'Honda',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            71 => [
                'id'         => 72,
                'creator_id' => 2,
                'name'       => 'Hongqi',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            72 => [
                'id'         => 73,
                'creator_id' => 2,
                'name'       => 'Hummer',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            73 => [
                'id'         => 74,
                'creator_id' => 2,
                'name'       => 'INEOS',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            74 => [
                'id'         => 75,
                'creator_id' => 2,
                'name'       => 'Infiniti',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            75 => [
                'id'         => 76,
                'creator_id' => 2,
                'name'       => 'Isuzu',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            76 => [
                'id'         => 77,
                'creator_id' => 2,
                'name'       => 'Iveco',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            77 => [
                'id'         => 78,
                'creator_id' => 2,
                'name'       => 'JAC',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            78 => [
                'id'         => 79,
                'creator_id' => 2,
                'name'       => 'Jaguar',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            79 => [
                'id'         => 80,
                'creator_id' => 2,
                'name'       => 'Jeep',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            80 => [
                'id'         => 81,
                'creator_id' => 2,
                'name'       => 'Koenigsegg',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            81 => [
                'id'         => 82,
                'creator_id' => 2,
                'name'       => 'KTM',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            82 => [
                'id'         => 83,
                'creator_id' => 2,
                'name'       => 'Lada',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            83 => [
                'id'         => 84,
                'creator_id' => 2,
                'name'       => 'Lamborghini',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            84 => [
                'id'         => 85,
                'creator_id' => 2,
                'name'       => 'Lancia',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            85 => [
                'id'         => 86,
                'creator_id' => 2,
                'name'       => 'Land Rover',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            86 => [
                'id'         => 87,
                'creator_id' => 2,
                'name'       => 'Landwind',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            87 => [
                'id'         => 88,
                'creator_id' => 2,
                'name'       => 'LEVC',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            88 => [
                'id'         => 89,
                'creator_id' => 2,
                'name'       => 'Lexus',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            89 => [
                'id'         => 90,
                'creator_id' => 2,
                'name'       => 'Ligier',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            90 => [
                'id'         => 91,
                'creator_id' => 2,
                'name'       => 'Lincoln',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            91 => [
                'id'         => 92,
                'creator_id' => 2,
                'name'       => 'Lotus',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            92 => [
                'id'         => 93,
                'creator_id' => 2,
                'name'       => 'Lucid',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            93 => [
                'id'         => 94,
                'creator_id' => 2,
                'name'       => 'Lynk & Co',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            94 => [
                'id'         => 95,
                'creator_id' => 2,
                'name'       => 'Mahindra',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            95 => [
                'id'         => 96,
                'creator_id' => 2,
                'name'       => 'MAN',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            96 => [
                'id'         => 97,
                'creator_id' => 2,
                'name'       => 'Maserati',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            97 => [
                'id'         => 98,
                'creator_id' => 2,
                'name'       => 'Maxus',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            98 => [
                'id'         => 99,
                'creator_id' => 2,
                'name'       => 'Maybach',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            99 => [
                'id'         => 100,
                'creator_id' => 2,
                'name'       => 'Mazda',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            100 => [
                'id'         => 101,
                'creator_id' => 2,
                'name'       => 'McLaren',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            101 => [
                'id'         => 102,
                'creator_id' => 2,
                'name'       => 'MG',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            102 => [
                'id'         => 103,
                'creator_id' => 2,
                'name'       => 'Microcar',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            103 => [
                'id'         => 104,
                'creator_id' => 2,
                'name'       => 'Microlino',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            104 => [
                'id'         => 105,
                'creator_id' => 2,
                'name'       => 'Mitsubishi',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            105 => [
                'id'         => 106,
                'creator_id' => 2,
                'name'       => 'Morgan',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            106 => [
                'id'         => 107,
                'creator_id' => 2,
                'name'       => 'NIO',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            107 => [
                'id'         => 108,
                'creator_id' => 2,
                'name'       => 'NSU',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            108 => [
                'id'         => 109,
                'creator_id' => 2,
                'name'       => 'Oldsmobile',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            109 => [
                'id'         => 110,
                'creator_id' => 2,
                'name'       => 'ORA',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            110 => [
                'id'         => 111,
                'creator_id' => 2,
                'name'       => 'Pagani',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            111 => [
                'id'         => 112,
                'creator_id' => 2,
                'name'       => 'Piaggio',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            112 => [
                'id'         => 113,
                'creator_id' => 2,
                'name'       => 'Plymouth',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            113 => [
                'id'         => 114,
                'creator_id' => 2,
                'name'       => 'Polestar',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            114 => [
                'id'         => 115,
                'creator_id' => 2,
                'name'       => 'Pontiac',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            115 => [
                'id'         => 116,
                'creator_id' => 2,
                'name'       => 'Porsche',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            116 => [
                'id'         => 117,
                'creator_id' => 2,
                'name'       => 'Proton',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            117 => [
                'id'         => 118,
                'creator_id' => 2,
                'name'       => 'Rolls-Royce',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            118 => [
                'id'         => 119,
                'creator_id' => 2,
                'name'       => 'Rover',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            119 => [
                'id'         => 120,
                'creator_id' => 2,
                'name'       => 'Ruf',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            120 => [
                'id'         => 121,
                'creator_id' => 2,
                'name'       => 'Saab',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            121 => [
                'id'         => 122,
                'creator_id' => 2,
                'name'       => 'Santana',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            122 => [
                'id'         => 123,
                'creator_id' => 2,
                'name'       => 'Seres',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            123 => [
                'id'         => 124,
                'creator_id' => 2,
                'name'       => 'Smart',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            124 => [
                'id'         => 125,
                'creator_id' => 2,
                'name'       => 'speedART',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            125 => [
                'id'         => 126,
                'creator_id' => 2,
                'name'       => 'Spyker',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            126 => [
                'id'         => 127,
                'creator_id' => 2,
                'name'       => 'Ssangyong',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            127 => [
                'id'         => 128,
                'creator_id' => 2,
                'name'       => 'Subaru',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            128 => [
                'id'         => 129,
                'creator_id' => 2,
                'name'       => 'Suzuki',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            129 => [
                'id'         => 130,
                'creator_id' => 2,
                'name'       => 'SWM',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            130 => [
                'id'         => 131,
                'creator_id' => 2,
                'name'       => 'Talbot',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            131 => [
                'id'         => 132,
                'creator_id' => 2,
                'name'       => 'Tata',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            132 => [
                'id'         => 133,
                'creator_id' => 2,
                'name'       => 'TECHART',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            133 => [
                'id'         => 134,
                'creator_id' => 2,
                'name'       => 'Tesla',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            134 => [
                'id'         => 135,
                'creator_id' => 2,
                'name'       => 'Trabant',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            135 => [
                'id'         => 136,
                'creator_id' => 2,
                'name'       => 'Triumph',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            136 => [
                'id'         => 137,
                'creator_id' => 2,
                'name'       => 'TVR',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            137 => [
                'id'         => 138,
                'creator_id' => 2,
                'name'       => 'VinFast',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            138 => [
                'id'         => 139,
                'creator_id' => 2,
                'name'       => 'Wartburg',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            139 => [
                'id'         => 140,
                'creator_id' => 2,
                'name'       => 'Westfield',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            140 => [
                'id'         => 141,
                'creator_id' => 2,
                'name'       => 'WEY',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            141 => [
                'id'         => 142,
                'creator_id' => 2,
                'name'       => 'Wiesmann',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            142 => [
                'id'         => 143,
                'creator_id' => 2,
                'name'       => 'XEV',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            143 => [
                'id'         => 144,
                'creator_id' => 2,
                'name'       => 'XPENG',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            144 => [
                'id'         => 145,
                'creator_id' => 2,
                'name'       => 'Zeekr',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
            145 => [
                'id'         => 146,
                'creator_id' => 2,
                'name'       => 'Zhidou',
                'created_at' => '2025-01-03 09:36:23',
                'updated_at' => null,
            ],
        ];

        DB::table('makes')->insert($makesArray);
    }
}
