/* This file is generated by Ziggy. */
declare module "ziggy-js" {
    interface RouteList {
        "debugbar.openhandler": [];
        "debugbar.clockwork": [
            {
                name: "id";
                required: true;
            }
        ];
        "debugbar.assets.css": [];
        "debugbar.assets.js": [];
        "debugbar.cache.delete": [
            {
                name: "key";
                required: true;
            },
            {
                name: "tags";
                required: false;
            }
        ];
        "sanctum.csrf-cookie": [];
        "ignition.healthCheck": [];
        "ignition.executeSolution": [];
        "ignition.updateConfig": [];
        dashboard: [];
        language: [
            {
                name: "locale";
                required: true;
            }
        ];
        "profile.edit": [];
        "profile.update": [];
        "profile.updateImage": [];
        "profile.destroy": [];
        "notifications.index": [];
        "notifications.read": [
            {
                name: "id";
                required: true;
            }
        ];
        "vehicles.index": [];
        "vehicles.create": [];
        "vehicles.store": [];
        "vehicles.show": [
            {
                name: "vehicle";
                required: true;
                binding: "id";
            }
        ];
        "vehicles.edit": [
            {
                name: "vehicle";
                required: true;
                binding: "id";
            }
        ];
        "vehicles.update": [
            {
                name: "vehicle";
                required: true;
                binding: "id";
            }
        ];
        "vehicles.destroy": [
            {
                name: "vehicle";
                required: true;
                binding: "id";
            }
        ];
        overview: [];
        "vehicles.duplicate": [];
        "vehicles.sales-order": [
            {
                name: "vehicle";
                required: true;
                binding: "id";
            }
        ];
        "pre-order-vehicles.index": [];
        "pre-order-vehicles.create": [];
        "pre-order-vehicles.store": [];
        "pre-order-vehicles.show": [
            {
                name: "pre_order_vehicle";
                required: true;
            }
        ];
        "pre-order-vehicles.edit": [
            {
                name: "pre_order_vehicle";
                required: true;
            }
        ];
        "pre-order-vehicles.update": [
            {
                name: "pre_order_vehicle";
                required: true;
            }
        ];
        "pre-order-vehicles.destroy": [
            {
                name: "pre_order_vehicle";
                required: true;
            }
        ];
        "service-vehicles.index": [];
        "service-vehicles.create": [];
        "service-vehicles.store": [];
        "service-vehicles.show": [
            {
                name: "service_vehicle";
                required: true;
            }
        ];
        "service-vehicles.edit": [
            {
                name: "service_vehicle";
                required: true;
            }
        ];
        "service-vehicles.update": [
            {
                name: "service_vehicle";
                required: true;
            }
        ];
        "service-vehicles.destroy": [
            {
                name: "service_vehicle";
                required: true;
            }
        ];
        "engines.index": [];
        "engines.create": [];
        "engines.store": [];
        "engines.show": [
            {
                name: "engine";
                required: true;
                binding: "id";
            }
        ];
        "engines.edit": [
            {
                name: "engine";
                required: true;
                binding: "id";
            }
        ];
        "engines.update": [
            {
                name: "engine";
                required: true;
                binding: "id";
            }
        ];
        "engines.destroy": [
            {
                name: "engine";
                required: true;
                binding: "id";
            }
        ];
        "variants.index": [];
        "variants.create": [];
        "variants.store": [];
        "variants.show": [
            {
                name: "variant";
                required: true;
                binding: "id";
            }
        ];
        "variants.edit": [
            {
                name: "variant";
                required: true;
                binding: "id";
            }
        ];
        "variants.update": [
            {
                name: "variant";
                required: true;
                binding: "id";
            }
        ];
        "variants.destroy": [
            {
                name: "variant";
                required: true;
                binding: "id";
            }
        ];
        "makes.index": [];
        "makes.create": [];
        "makes.store": [];
        "makes.show": [
            {
                name: "make";
                required: true;
                binding: "id";
            }
        ];
        "makes.edit": [
            {
                name: "make";
                required: true;
                binding: "id";
            }
        ];
        "makes.update": [
            {
                name: "make";
                required: true;
                binding: "id";
            }
        ];
        "makes.destroy": [
            {
                name: "make";
                required: true;
                binding: "id";
            }
        ];
        "vehicle-models.index": [];
        "vehicle-models.create": [];
        "vehicle-models.store": [];
        "vehicle-models.show": [
            {
                name: "vehicle_model";
                required: true;
            }
        ];
        "vehicle-models.edit": [
            {
                name: "vehicle_model";
                required: true;
            }
        ];
        "vehicle-models.update": [
            {
                name: "vehicle_model";
                required: true;
            }
        ];
        "vehicle-models.destroy": [
            {
                name: "vehicle_model";
                required: true;
            }
        ];
        "vehicle-groups.index": [];
        "vehicle-groups.create": [];
        "vehicle-groups.store": [];
        "vehicle-groups.show": [
            {
                name: "vehicle_group";
                required: true;
            }
        ];
        "vehicle-groups.edit": [
            {
                name: "vehicle_group";
                required: true;
            }
        ];
        "vehicle-groups.update": [
            {
                name: "vehicle_group";
                required: true;
            }
        ];
        "vehicle-groups.destroy": [
            {
                name: "vehicle_group";
                required: true;
            }
        ];
        "items.index": [];
        "items.create": [];
        "items.store": [];
        "items.show": [
            {
                name: "item";
                required: true;
                binding: "id";
            }
        ];
        "items.edit": [
            {
                name: "item";
                required: true;
                binding: "id";
            }
        ];
        "items.update": [
            {
                name: "item";
                required: true;
                binding: "id";
            }
        ];
        "items.destroy": [
            {
                name: "item";
                required: true;
                binding: "id";
            }
        ];
        "crm.companies.index": [];
        "crm.companies.create": [];
        "crm.companies.store": [];
        "crm.companies.show": [
            {
                name: "company";
                required: true;
            }
        ];
        "crm.companies.edit": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "crm.companies.update": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "crm.companies.destroy": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "crm.company-groups.index": [];
        "crm.company-groups.create": [];
        "crm.company-groups.store": [];
        "crm.company-groups.show": [
            {
                name: "company_group";
                required: true;
            }
        ];
        "crm.company-groups.edit": [
            {
                name: "company_group";
                required: true;
            }
        ];
        "crm.company-groups.update": [
            {
                name: "company_group";
                required: true;
            }
        ];
        "crm.company-groups.destroy": [
            {
                name: "company_group";
                required: true;
            }
        ];
        "crm.users.index": [];
        "crm.users.create": [];
        "crm.users.store": [];
        "crm.users.show": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "crm.users.edit": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "crm.users.update": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "crm.users.destroy": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "crm.user-groups.index": [];
        "crm.user-groups.create": [];
        "crm.user-groups.store": [];
        "crm.user-groups.show": [
            {
                name: "user_group";
                required: true;
            }
        ];
        "crm.user-groups.edit": [
            {
                name: "user_group";
                required: true;
            }
        ];
        "crm.user-groups.update": [
            {
                name: "user_group";
                required: true;
            }
        ];
        "crm.user-groups.destroy": [
            {
                name: "user_group";
                required: true;
            }
        ];
        "purchase-orders.index": [];
        "purchase-orders.create": [];
        "purchase-orders.store": [];
        "purchase-orders.show": [
            {
                name: "purchase_order";
                required: true;
            }
        ];
        "purchase-orders.edit": [
            {
                name: "purchase_order";
                required: true;
            }
        ];
        "purchase-orders.update": [
            {
                name: "purchase_order";
                required: true;
            }
        ];
        "purchase-orders.destroy": [
            {
                name: "purchase_order";
                required: true;
            }
        ];
        "purchase-orders.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "pre-orders.index": [];
        "pre-orders.create": [];
        "pre-orders.store": [];
        "pre-orders.show": [
            {
                name: "pre_order";
                required: true;
            }
        ];
        "pre-orders.edit": [
            {
                name: "pre_order";
                required: true;
            }
        ];
        "pre-orders.update": [
            {
                name: "pre_order";
                required: true;
            }
        ];
        "pre-orders.destroy": [
            {
                name: "pre_order";
                required: true;
            }
        ];
        "pre-orders.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "pre-orders.vehicles": [
            {
                name: "id";
                required: true;
            }
        ];
        "sales-orders.index": [];
        "sales-orders.create": [];
        "sales-orders.store": [];
        "sales-orders.show": [
            {
                name: "sales_order";
                required: true;
            }
        ];
        "sales-orders.edit": [
            {
                name: "sales_order";
                required: true;
            }
        ];
        "sales-orders.update": [
            {
                name: "sales_order";
                required: true;
            }
        ];
        "sales-orders.destroy": [
            {
                name: "sales_order";
                required: true;
            }
        ];
        "sales-orders.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "service-orders.index": [];
        "service-orders.create": [];
        "service-orders.store": [];
        "service-orders.show": [
            {
                name: "service_order";
                required: true;
            }
        ];
        "service-orders.edit": [
            {
                name: "service_order";
                required: true;
            }
        ];
        "service-orders.update": [
            {
                name: "service_order";
                required: true;
            }
        ];
        "service-orders.destroy": [
            {
                name: "service_order";
                required: true;
            }
        ];
        "service-orders.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "workflows.index": [];
        "workflows.create": [];
        "workflows.store": [];
        "workflows.show": [
            {
                name: "workflow";
                required: true;
                binding: "id";
            }
        ];
        "workflows.edit": [
            {
                name: "workflow";
                required: true;
                binding: "id";
            }
        ];
        "workflows.update": [
            {
                name: "workflow";
                required: true;
                binding: "id";
            }
        ];
        "workflows.destroy": [
            {
                name: "workflow";
                required: true;
                binding: "id";
            }
        ];
        "workflow-finished-steps.index": [];
        "workflow-finished-steps.create": [];
        "workflow-finished-steps.store": [];
        "workflow-finished-steps.show": [
            {
                name: "workflow_finished_step";
                required: true;
            }
        ];
        "workflow-finished-steps.edit": [
            {
                name: "workflow_finished_step";
                required: true;
            }
        ];
        "workflow-finished-steps.update": [
            {
                name: "workflow_finished_step";
                required: true;
            }
        ];
        "workflow-finished-steps.destroy": [
            {
                name: "workflow_finished_step";
                required: true;
            }
        ];
        "work-orders.index": [];
        "work-orders.create": [];
        "work-orders.store": [];
        "work-orders.show": [
            {
                name: "work_order";
                required: true;
            }
        ];
        "work-orders.edit": [
            {
                name: "work_order";
                required: true;
            }
        ];
        "work-orders.update": [
            {
                name: "work_order";
                required: true;
            }
        ];
        "work-orders.destroy": [
            {
                name: "work_order";
                required: true;
            }
        ];
        "work-order-tasks.index": [];
        "work-order-tasks.create": [];
        "work-order-tasks.store": [];
        "work-order-tasks.show": [
            {
                name: "work_order_task";
                required: true;
            }
        ];
        "work-order-tasks.edit": [
            {
                name: "work_order_task";
                required: true;
            }
        ];
        "work-order-tasks.update": [
            {
                name: "work_order_task";
                required: true;
            }
        ];
        "work-order-tasks.destroy": [
            {
                name: "work_order_task";
                required: true;
            }
        ];
        "transport-orders.index": [];
        "transport-orders.create": [];
        "transport-orders.store": [];
        "transport-orders.show": [
            {
                name: "transport_order";
                required: true;
            }
        ];
        "transport-orders.edit": [
            {
                name: "transport_order";
                required: true;
            }
        ];
        "transport-orders.update": [
            {
                name: "transport_order";
                required: true;
            }
        ];
        "transport-orders.destroy": [
            {
                name: "transport_order";
                required: true;
            }
        ];
        "transport-orders.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "service-levels.index": [];
        "service-levels.create": [];
        "service-levels.store": [];
        "service-levels.show": [
            {
                name: "service_level";
                required: true;
            }
        ];
        "service-levels.edit": [
            {
                name: "service_level";
                required: true;
            }
        ];
        "service-levels.update": [
            {
                name: "service_level";
                required: true;
            }
        ];
        "service-levels.destroy": [
            {
                name: "service_level";
                required: true;
            }
        ];
        "documents.index": [];
        "documents.create": [];
        "documents.store": [];
        "documents.show": [
            {
                name: "document";
                required: true;
                binding: "id";
            }
        ];
        "documents.edit": [
            {
                name: "document";
                required: true;
                binding: "id";
            }
        ];
        "documents.update": [
            {
                name: "document";
                required: true;
                binding: "id";
            }
        ];
        "documents.destroy": [
            {
                name: "document";
                required: true;
                binding: "id";
            }
        ];
        "documents.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "quotes.index": [];
        "quotes.create": [];
        "quotes.store": [];
        "quotes.show": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quotes.edit": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quotes.update": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quotes.destroy": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quotes.stop": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quotes.status": [
            {
                name: "id";
                required: true;
            },
            {
                name: "status";
                required: true;
            }
        ];
        "quotes.duplicate": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quotes.sales-order": [
            {
                name: "quote";
                required: true;
                binding: "id";
            }
        ];
        "quote-invitations.create": [];
        "quote-invitations.store": [];
        "quote-invitations.edit": [
            {
                name: "quote_invitation";
                required: true;
            }
        ];
        "quote-invitations.update": [
            {
                name: "quote_invitation";
                required: true;
            }
        ];
        "quote-invitations.destroy": [
            {
                name: "quote_invitation";
                required: true;
            }
        ];
        "mails.index": [];
        "quote-invitations.index": [];
        "quote-invitations.show": [
            {
                name: "quote_invitation";
                required: true;
            }
        ];
        "quote-invitations.status": [
            {
                name: "id";
                required: true;
            }
        ];
        "quote-invitations.accept": [
            {
                name: "id";
                required: true;
            }
        ];
        "quote-invitations.reject": [
            {
                name: "id";
                required: true;
            }
        ];
        "quote-invitations.invitation": [
            {
                name: "quoteId";
                required: true;
            }
        ];
        "setting.index": [];
        "setting.create": [];
        "setting.store": [];
        "setting.show": [
            {
                name: "setting";
                required: true;
                binding: "id";
            }
        ];
        "setting.edit": [
            {
                name: "setting";
                required: true;
                binding: "id";
            }
        ];
        "setting.update": [
            {
                name: "setting";
                required: true;
                binding: "id";
            }
        ];
        "setting.destroy": [
            {
                name: "setting";
                required: true;
                binding: "id";
            }
        ];
        "companies.index": [];
        "companies.create": [];
        "companies.store": [];
        "companies.show": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "companies.edit": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "companies.update": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "companies.destroy": [
            {
                name: "company";
                required: true;
                binding: "id";
            }
        ];
        "users.index": [];
        "users.create": [];
        "users.store": [];
        "users.show": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "users.edit": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "users.update": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "users.destroy": [
            {
                name: "user";
                required: true;
                binding: "id";
            }
        ];
        "configurations.index": [];
        "configurations.create": [];
        "configurations.store": [];
        "configurations.show": [
            {
                name: "configuration";
                required: true;
                binding: "id";
            }
        ];
        "configurations.edit": [
            {
                name: "configuration";
                required: true;
                binding: "id";
            }
        ];
        "configurations.update": [
            {
                name: "configuration";
                required: true;
                binding: "id";
            }
        ];
        "configurations.destroy": [
            {
                name: "configuration";
                required: true;
                binding: "id";
            }
        ];
        "images.order": [];
        "images.destroy": [
            {
                name: "path";
                required: true;
            }
        ];
        "files.order": [];
        "files.download": [
            {
                name: "path";
                required: true;
            }
        ];
        "files.destroy": [
            {
                name: "path";
                required: true;
            }
        ];
        "pdf.send_mail": [];
        login: [];
        "password.request": [];
        "password.email": [];
        "password.reset": [
            {
                name: "token";
                required: true;
            }
        ];
        "password.store": [];
        "verification.notice": [];
        "verification.verify": [
            {
                name: "id";
                required: true;
            },
            {
                name: "hash";
                required: true;
            }
        ];
        "verification.send": [];
        "password.confirm": [];
        "password.update": [];
        "image.update": [];
        logout: [];
    }
}
export {};
