export enum Country {
    Austria = 1,
    Belgium = 2,
    Bulgaria = 3,
    Croatia = 4,
    Czech_Republic = 5,
    Denmark = 6,
    Finland = 7,
    France = 8,
    Germany = 9,
    Greece = 10,
    Hungary = 11,
    Ireland = 12,
    Italy = 13,
    Lithuania = 14,
    Luxembourg = 15,
    Netherlands = 16,
    Norway = 17,
    Poland = 18,
    Portugal = 19,
    Romania = 20,
    Serbia = 21,
    Slovakia = 22,
    Slovenia = 23,
    Switzerland = 24,
    Spain = 25,
    Sweden = 26,
}